export  const FETCH_ISSUES_SUCCESS = 'FETCH_ISSUES_SUCCESS';
export  const FETCH_SINGLE_ISSUE_SUCCESS = 'FETCH_SINGLE_ISSUE_SUCCESS';
export  const SORT_ISSUES_SUCCESS = 'SORT_ISSUES_SUCCESS';
export  const LOADING_ISSUES_SUCCESS = 'LOADING_ISSUES_SUCCESS';
export  const FETCH_ISSUES_ERROR = 'FETCH_ISSUES_ERROR';
export  const RESET_ERROR = 'RESET_ERROR';
export  const FILTER_ISSUES_SUCCESS = 'FILTER_ISSUES_SUCCESS';
export  const RESET_ISSUE_QUERY = 'RESET_ISSUE_QUERY';
export  const BACK_TO_ISSUE_PAGE = 'BACK_TO_ISSUE_PAGE';

