export  const FETCH_BOOKS_SUCCESS = 'FETCH_BOOKS_SUCCESS';
export  const GET_BOOK_SUCCESS = 'GET_BOOK_SUCCESS';
export  const CREATE_BOOK_SUCCESS = 'CREATE_BOOK_SUCCESS';
export  const EDIT_BOOK_SUCCESS = 'EDIT_BOOK_SUCCESS';
export  const DELETE_BOOK_SUCCESS = 'DELETE_BOOK_SUCCESS';
export  const FETCH_GENRES_SUCCESS = 'FETCH_GENRES_SUCCESS';
export  const GET_GENRE_SUCCESS = 'GET_GENRE';
export  const CREATE_GENRE_SUCCESS = 'CREATE_GENRE_SUCCESS';
export  const EDIT_GENRE_SUCCESS = 'EDIT_GENRE_SUCCESS';
export  const DELETE_GENRE_SUCCESS = 'DELETE_GENRE_SUCCESS';
export  const LOADING_BOOK_SUCCESS = 'LOADING_BOOK_SUCCESS';
export  const LOADING_GENRES_SUCCESS = 'LOADING_GENRES_SUCCESS';
export  const ERROR_OCCURED = 'ERROR_OCCURED';
export  const RESET_ERROR = 'RESET_ERROR';
export  const RESET_BOOK_STATE = 'RESET_CREATE_EDIT_STATE';
export  const RESET_GENRE_STATE = 'RESET_GENRE_STATE';

